### ISSUE TITLE
Environmental variables

### ISSUE THREAD

**Issue by kfrajtak** [Metalnem/sharpfuzz#10]
Hello,

great project! 

I was trying your example and I it did not work. I have noticed the code reading environmental variable `__AFL_SHM_ID` value to decide whether to run with/without AFL.

Can you tell me what should be the variable of `__AFL_SHM_ID` be?

Thanks.
Karel

**Comment by Metalnem** [comment]
Hi! __AFL_SHM_ID is set by afl-fuzz, and users shouldn’t even be aware that it exists. Your problem is most likely somewhere else. Which step exactly didn’t work for you?

**Comment by kfrajtak** [comment]
I see, I was curious and started debugging the project.

**Comment by kfrajtak** [comment]
I see, I was curious and started debugging the project.

**Comment by Metalnem** [comment]
I guess then that there is no issue here.
