### ISSUE TITLE
Fork server handshake failed issue on Jil.dll

### ISSUE THREAD

**Issue by nvivekk** [Metalnem/sharpfuzz#16]
I am getting stuck on the following issue:

```
_[-] PROGRAM ABORT : Fork server handshake failed
         Location : init_forkserver(), afl-fuzz.c:2253_
```

I'm using AFL 2.56b, With dotnet 3.1.202 in parrot OS 4.7. My csproj-file contains this:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Jil">
      <HintPath>Jil.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SharpFuzz" Version="1.6.2" />
    <PackageReference Include="Sigil" Version="4.7.0" />
  </ItemGroup>
</Project>
```

Command I used : `[_afl-fuzz -i testcases_dir -o findings_dir -t 5000 -m 10000 dotnet path_to_assembly_](url)`

Following is result after the command 
```
[+] You have 4 CPU cores and 3 runnable tasks (utilization: 75%).
[+] Try parallel jobs - see /usr/local/share/doc/afl/parallel_fuzzing.txt.
[*] Checking CPU core loadout...
[+] Found a free CPU core, binding to #0.
[*] Checking core_pattern...
[*] Checking CPU scaling governor...
[*] Setting up output directories...
[+] Output directory exists but deemed OK to reuse.
[*] Deleting old session data...
[+] Output dir cleanup successful.
[*] Scanning 'Testcases'...
[+] No auto-generated dictionary tokens to reuse.
[*] Creating hard links for all input files...
[*] Validating target binary...
[*] Attempting dry run with 'id:000000,orig:test.json'...
[*] Spinning up the fork server...

[-] Hmm, looks like the target binary terminated before we could complete a
    handshake with the injected code. There are two probable explanations:
```
Can you help me to investigate.

**Comment by Jossec101** [comment]
I'm having a similar issue, but it stopped working from me when I moved from WSL1 to WSL2 (Ubuntu 20.04).

I did ulimit -Sv $[999 << 10];  dotnet bin/fuzzed_app.dll and this appears:

```Failed to create CoreCLR, HRESULT: 0x8007000E```

From https://github.com/dotnet/runtime/issues/13027 It looks that It may be a problem with the ram,  but if I write ```ulimit -v``` I get ```unlimited```

I will keep investigating but this may help you @nvivekk 

Any idea @Metalnem ?

Thanks!

**Comment by Metalnem** [comment]
@nvivekk, did you instrument `Jil.dll` by running `sharpfuzz Jil.dll` command on it? Also, can you share your main program (even better would be if you could attach the whole project)?

@Jossec101, I have no idea what could be causing your issue. If it was working on WSL1, and now it's not on WSL2, I doubt the issue is in SharpFuzz.

**Comment by nvivekk** [comment]
Yeah I have ran Jil.dll with sharpfuzz command before starting the fuzz. 
I have uploaded my project folder. [test.zip](https://github.com/Metalnem/sharpfuzz/files/4751532/test.zip)

@Jossec101 I am trying it on linux distro. So WSL2 may not be an issue here. 

Thanks for the reponse.  @Metalnem

**Comment by CityOfLight77** [comment]
I'm using dotnet 6.0 on ubuntu 20.04 with 2GB RAM and got `Fork server handshake failed`

Here is my step to run afl-fuzz @Metalnem 
```sh
git clone https://github.com/Metalnem/sharpfuzz-samples.git
cd sharpfuzz-samples/Newtonsoft.Json/Newtonsoft.Json.Fuzz
wget https://www.nuget.org/api/v2/package/Newtonsoft.Json/13.0.2-beta1
mv 13.0.2-beta1 13.0.2-beta1.zip; unzip 13.0.2-beta1.zip -d Newtonsoft13beta
# cp 13.0.2-beta1/lib/net6.0/* .
sharpfuzz Newtonsoft13beta/lib/netstandard2.0/Newtonsoft.Json.dll
dotnet add package SharpFuzz
# prepare corpus
mkdir input; mkdir tmpinput; mkdir output
echo '{"a": "b"}' > input/a.json
wget https://raw.githubusercontent.com/AFLplusplus/AFLplusplus/stable/dictionaries/json.dict
dotnet build
afl-fuzz -i input/ -o output -m none -t 5000 -x json.dict dotnet bin/Debug/netcoreapp2.2/Newtonsoft.Json.Fuzz.dll
```
