### ISSUE TITLE
OpenMcdf

### ISSUE THREAD

**Issue by Numpsy** [Metalnem/sharpfuzz#2]
Hi,
Saw the note on the front page about trophies, so in case you're interested:

I tried running [OpenMcdf](https://github.com/ironfede/openmcdf) through SharpFuzz, and it generated a few files that caused ArgumentOutOfRangeException and 2 that caused OutOfMemoryException: 

https://github.com/ironfede/openmcdf/issues/40
https://github.com/ironfede/openmcdf/issues/39
https://github.com/ironfede/openmcdf/issues/38
https://github.com/ironfede/openmcdf/issues/30 (generated a file that repros a known issue that had no test case attached).

Thanks for the nice tool :-)

**Comment by Metalnem** [comment]
Of course I'm interested, thanks for the reports :)
