### ISSUE TITLE
afl-showmap - No instrumentation detected

### ISSUE THREAD

**Issue by c0ld21** [Metalnem/sharpfuzz#20]
Is there currently a way to use afl-showmap on an instrumented .NET DLL? I get "No instrumentation detected" when trying afl-showmap, I also tried running it with AFL_SKIP_BIN_CHECK=1. 

If not, are there any potential workarounds to verify edge IDs?

**Comment by CityOfLight77** [comment]
@Metalnem I have same issue No instrumentationd detected when running sharpfuzz with and without `AFL_SKIP_BIN_CHECK=1`

**Comment by paintedveil5** [comment]
@c0ld21 @CityOfLight77 Me too. Have you solved it?

**Comment by c0ld21** [comment]
iirc, we just used our in-house showmap add-on

**Comment by c0ld21** [comment]
> @c0ld21 @CityOfLight77 Me too. Have you solved it?

iirc, we just used our in-house showmap add-on

**Comment by martinknafvework** [comment]
Old thread but replying in case someone else runs into the same issue: If you follow the instructions in the readme, it tells you to create a console app which calls `Fuzzer.OutOfProcess.Run`. When you run `fuzz.ps1`, the console application binary will be excluded from instrumentation. This means that if if you add the logic you want to fuzz to the same project (the console app), you will get this error. 

If you are trying to fuzz some 3rd party library you would not run into this issue, but if you are just playing around with SharpFuzz or if you're trying to fuzz some local code you're working on, you might place the code you want to fuzz into the same console app project. To solve it you would need to create a separate class library with the code you want to test.
