### ISSUE TITLE
Timeout proccesing

### ISSUE THREAD

**Issue by gfarida** [Metalnem/sharpfuzz#23]
Hi! Could yo help me and say where timeout does process in your code? I found only crashes processing. Thank you!

**Comment by gfarida** [comment]
Thank you! I see. So why did you use "Timeout" field in Fault class?

**Comment by Metalnem** [comment]
Just to match the enum definition from AFL (even though SharpFuzz doesn't use the timeout status itself):
https://github.com/google/AFL/blob/61037103ae3722c8060ff7082994836a794f978e/afl-fuzz.c#L330
