### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by gfarida** [Metalnem/sharpfuzz#25]
Is Sharpfuzz available on windows?

**Comment by Metalnem** [comment]
Yes! Latest SharpFuzz release (2.0.0) supports libFuzzer on Windows (https://github.com/Metalnem/sharpfuzz/pull/24).

SharpFuzz documentation for libFuzzer (https://github.com/Metalnem/sharpfuzz/blob/master/docs/libFuzzer.md) still doesn't have the necessary instructions for using it on Windows, though. I plan to fix that, but I don't know yet when it will happen.

**Comment by Metalnem** [comment]
Actually, I think @ranweiler already wrote the documentation :)
https://github.com/microsoft/onefuzz/blob/main/src/agent/LibFuzzerDotnetLoader/README.md

**Comment by ranweiler** [comment]
> Actually, I think @ranweiler already wrote the documentation :) https://github.com/microsoft/onefuzz/blob/main/src/agent/LibFuzzerDotnetLoader/README.md

☺️ Note for end users: these docs are mostly for an _auxiliary_ project that is part of OneFuzz, and mostly describe additional features that require that project.

However, [this](https://github.com/microsoft/onefuzz/blob/28e42ab8e85bd0db612d1a3e3e8fe0626e579a95/src/agent/LibFuzzerDotnetLoader/README.md#build-libfuzzer-dotnet) section is still relevant, and replaces Step 4 in the main docs. The only difference when using SharpFuzz on Windows that you need to compile a different source file to get `libfuzzer-dotnet.exe`.

**Comment by gfarida** [comment]
Hello, @ranweiler and @Metalnem! I don't understand how the fuzzer knows that the program's status is CRUSH. When does he recieve "2" through the channel? Or how? Because there is no SIGSEGV, SIGABRT, SIGILL in Windows.
Thanks for your reply!

**Comment by Metalnem** [comment]
Fuzzer executes the user-provided function inside the try-catch block. If it catches an exception, it reports it as a crash to the fuzzing backend:

https://github.com/Metalnem/sharpfuzz/blob/master/src/SharpFuzz/Fuzzer.cs#L359
