### ISSUE TITLE
Question about excuting action sharpfuzz/src/SharpFuzz/Fuzzer.LibFuzzer.cs

### ISSUE THREAD

**Issue by gfarida** [Metalnem/sharpfuzz#27]
Hi! I have a question about these lines: https://github.com/Metalnem/sharpfuzz/blob/245c6ae1b10e484be1ef440b0d23c1cfbaf2913c/src/SharpFuzz/Fuzzer.LibFuzzer.cs#L62 What is data here? And why don't you work with stream like this: https://github.com/Metalnem/sharpfuzz/blob/245c6ae1b10e484be1ef440b0d23c1cfbaf2913c/src/SharpFuzz/Fuzzer.OutOfProcess.cs#L213

And second question: I can not find place (in sharpfuzz for windows) where you fill bitmap with run information. Can you show me it?

Thank you for replies!

**Comment by Metalnem** [comment]
Hi @gfarida!

>What is data here? And why don't you work with stream like this:

`afl-fuzz` passes the input data using the standard input, while my `libFuzzer` driver is using shared memory. You can see how it's implemented here:

https://github.com/Metalnem/libfuzzer-dotnet/blob/master/libfuzzer-dotnet.cc#L204

>And second question: I can not find place (in sharpfuzz for windows) where you fill bitmap with run information. Can you show me it?

If I understand the question correctly, it's these four lines (for both Windows and Posix):

https://github.com/Metalnem/sharpfuzz/blob/master/src/SharpFuzz/Fuzzer.LibFuzzer.cs#L40

`FuzzerIpc` constructor reads the ID of the shared memory segment where trace bitmap is located, and then `TraceWrapper` is created on that segment and filled by `SharpFuzz`.
