### ISSUE TITLE
Question regarding plans for SharpFuzz with libFuzzer on macOS

### ISSUE THREAD

**Issue by sijohans** [Metalnem/sharpfuzz#28]
Hello,

As stated in https://github.com/Metalnem/sharpfuzz/blob/master/docs/libFuzzer.md support for mac and windows is coming soon. What is the status of this? What is needed to do this, any way one could help?

**Comment by Metalnem** [comment]
Hi @sijohans!

Support for Windows already exists:
https://github.com/Metalnem/libfuzzer-dotnet/blob/master/libfuzzer-dotnet-windows.cc

I never used it, though, but I think it should be simple:
https://github.com/microsoft/onefuzz/tree/main/src/agent/LibFuzzerDotnetLoader#windows

```bash
clang -g -O2 -fsanitize=fuzzer libfuzzer-dotnet-windows.cc -o libfuzzer-dotnet.exe
```

If you are interested in helping, you could try this and document the process if you can make it work :)

**Comment by Metalnem** [comment]
Hi @sijohans!

Windows support is ready! Here are the instructions:
https://github.com/Metalnem/sharpfuzz/blob/master/docs/libFuzzer.md

If they are not clear enough, or you think I should add something, feel free to create an issue or a PR with the suggestions.

macOS will unfortunately not be supported (I don't know how to make [__libfuzzer_extra_counters](https://github.com/Metalnem/libfuzzer-dotnet/blob/master/libfuzzer-dotnet.cc#LL24) work on macOS).
