### ISSUE TITLE
Test .net Application Console program

### ISSUE THREAD

**Issue by moru46** [Metalnem/sharpfuzz#30]
Hi everybody, 
I'm pretty new to the world of fuzzing and was trying to test my program with afl.
I've already done tests and trials with afl, especially in Blackbox mode with qemu because my program runs on .NET.
Seeing this repo I wanted to try to use Sharpfuzz with my program, however after several unsuccessful attempts I decided to try to ask you.
First of all my doubt is if Sharpfuzz can be used to test complex programs (in my case it is an Application console program, which runs on .NET Core) because in the examples that I found in this repo, there are only .NET library tests.

In my attempts with Sharpfuzz I still tried to include a main with the Fuzzer.run function which is required, however I keep getting runtime problems, from the method that calls the stream to read what is passed in input.
I'm referring to the function on **line 234 of the src/SharpFuzz/Fuzzer.cs** : 
**file using (var stream = new UnclosableStreamWrapper(stdin)).**
Since my program reads from files etc I tried different ways to make it work, either by passing the path, or by modifying the code and passing the content directly to stream, however the function fails every time at that particular point.

Finally, the last doubt concerns the instrumentation part of the .dll: in the examples the .dll libraries are obviously instrumented because  we want to test them, however in a more complex program, how can I do to instrument those parts of code that I would like to test, if are the various binary .dlls created at compile time?

For this reason I have the doubt that Sharpfuzz is currently only useful for testing .NET libraries.

thanks in advance to whoever will answer me

**Comment by Metalnem** [comment]
Hi @moru46!

>Since my program reads from files etc I tried different ways to make it work, either by passing the path, or by modifying the code and passing the content directly to stream, however the function fails every time at that particular point.

Can you attach some repro to this ticket, so I could try to troubleshoot what's wrong with your use case?

>however in a more complex program, how can I do to instrument those parts of code that I would like to test, if are the various binary .dlls created at compile time?

Not sure that I understand this question, can you please elaborate more? You can instrument as many .dlls as you want, but I'm not sure that answers the question you asked.
