### ISSUE TITLE
document hidden env variables and features

### ISSUE THREAD

**Issue by fuzzah** [Metalnem/sharpfuzz#35]
Please document hidden features of SharpFuzz.

# Env vars
`SHARPFUZZ_PRINT_INSTRUMENTED_TYPES` - self-explanatory, but still undocumented. Displays types and methods instrumented.
`SHARPFUZZ_ENABLE_ON_BRANCH_CALLBACK` - seems to just crash the target right away with null pointer exception. Does sharpfuzz NOT instrument branches by default?

# Run args
Exclude classes you don't want to instrument:
```sharpfuzz path/to/some_assembly.dll IncludeFilter -ExcludeFilter```
Can filter out multiple matches:
```sharpfuzz path/to/some_assembly.dll IncludeFilter -ExcludeFilter,Exclude2,Exclude3```

I might have missed something.

**Comment by Metalnem** [comment]
Hi @fuzzah!

Hidden features of SharpFuzz are hidden for a reason :) That is, there is no good reason for regular SharpFuzz users to use them, and documenting them would make things more confusing. Also, I don't want anyone to depend on them.

`SHARPFUZZ_ENABLE_ON_BRANCH_CALLBACK ` - SharpFuzz does instrument everything by default, this flag doesn't change that. What this flag does is that it allows you to set your own callback that will get called at every instrumented branch, along with regular instrumentation. If you instrument your assembly with the flag enabled, then you need to do this before calling `Fuzzer.Run`:

```csharp
SharpFuzz.Common.Trace.OnBranch = (branchId, functionName) => {
  // do whatever you want here
};
```

The reason you were getting a null pointer exception was that `OnBranch` callback was null.

**Comment by fuzzah** [comment]
@Metalnem , thanks for the reply!
Consider documenting at least the filtering features as these are really useful for better control of the fuzzing scope.
I can prepare the PR if you're busy :)

**Comment by Metalnem** [comment]
I don't have the time, but if you want to prepare the PR, I'm all for it :) Can you create a separate page and link it in the **Advanced topics** section of the README file?

If you want, you can even include `SHARPFUZZ_PRINT_INSTRUMENTED_TYPES` in that page.
