### ISSUE TITLE
PDF Clown / PdfPig

### ISSUE THREAD

**Issue by Numpsy** [Metalnem/sharpfuzz#6]
Hi,

In case you're interested:

I tried running [PDF Clown](https://pdfclown.org/) through sharpfuzz a while ago and it generated a .pdf file that causes a StackOverflowException on open, but as that library is unsupported I didn't do anything with it.

However, I more recently tried opening that same file in [PdfPig](https://github.com/UglyToad/PdfPig) and found it also causes a StackOverflowException there - https://github.com/UglyToad/PdfPig/issues/33 - so a pair of bugs with one file.

**Comment by Metalnem** [comment]
Great finding, thanks! I've added it to the trophies list.
